-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 11:05:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinic_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinic_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinic_db` DEFAULT CHARACTER SET utf8 ;
USE `clinic_db` ;

-- -----------------------------------------------------
-- Table `clinic_db`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`paciente` (
  `id_paciente` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`especialidade` (
  `id_especialidade` INT NOT NULL auto_increment,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`medico` (
  `id_medico` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `crm` VARCHAR(45) NOT NULL,
  `especialidade` INT NOT NULL,
  PRIMARY KEY (`id_medico`),
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC) VISIBLE,
  INDEX `fk_medico_especialidade_idx` (`especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_medico_especialidade`
    FOREIGN KEY (`especialidade`)
    REFERENCES `clinic_db`.`especialidade` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`consulta` (
  `id_consulta` INT NOT NULL auto_increment,
  `data_consulta` DATE NOT NULL,
  `observacoes` LONGTEXT NULL,
  `paciente` INT NOT NULL,
  `medico` INT NOT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_consulta_paciente1_idx` (`paciente` ASC) VISIBLE,
  INDEX `fk_consulta_medico1_idx` (`medico` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`paciente`)
    REFERENCES `clinic_db`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_medico1`
    FOREIGN KEY (`medico`)
    REFERENCES `clinic_db`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`exame` (
  `id_exame` INT NOT NULL auto_increment,
  `nome_exame` VARCHAR(100) NOT NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`id_exame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`funcionario` (
  `id_funcionario` INT NOT NULL auto_increment,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinic_db`.`solicitacaoExame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinic_db`.`solicitacaoExame` (
  `id_solicitacao_exame` INT NOT NULL auto_increment,
  `data_solicitacao` DATE NOT NULL,
  `resultado` LONGTEXT NULL,
  `consulta` INT NOT NULL,
  `funcionario` INT NOT NULL,
  `exame` INT NOT NULL,
  PRIMARY KEY (`id_solicitacao_exame`),
  INDEX `fk_solicitacaoExame_consulta1_idx` (`consulta` ASC) VISIBLE,
  INDEX `fk_solicitacaoExame_funcionario1_idx` (`funcionario` ASC) VISIBLE,
  INDEX `fk_solicitacaoExame_exame1_idx` (`exame` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacaoExame_consulta1`
    FOREIGN KEY (`consulta`)
    REFERENCES `clinic_db`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacaoExame_funcionario1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `clinic_db`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacaoExame_exame1`
    FOREIGN KEY (`exame`)
    REFERENCES `clinic_db`.`exame` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


